#!/bin/sh

# ____                              
#| __ ) ___ _ ____      ___ __ ___  
#|  _ \/ __| '_ \ \ /\ / / '_ ` _ \ 
#| |_) \__ \ |_) \ V  V /| | | | | |
#|____/|___/ .__/ \_/\_/ |_| |_| |_|
#          |_| 


	  
#### AUTOSTART ####
sxhkd &
picom -b &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
~/.config/bspwm/scripts/startup &
~/.config/bspwm/scripts/pacman-updates.sh &
~/.config/bspwm/scripts/external_rules &
wmname LG3D &
#### BSPWM configuration ####
bspc config border_width		  0
bspc config window_gap                    15
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a steam desktop='^5' state=floating follow=on
bspc rule -a discord desktop='^6' follow=off
bspc rule -a android-studio desktop='^7' state=floating follow=off
#### monitor configuration ####
bspc monitor eDP-1 -d  1 2 3 4 5 6 7 8
